# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=100)),
                ('time_last', models.CharField(max_length=100)),
                ('confiance', models.CharField(max_length=100)),
                ('statut', models.CharField(max_length=100)),
            ],
        ),
    ]
